value_mapping:
    AED: United Arab Emirates Dirham
    AMD: Armenian Dram
    AUD: Australian Dollar
    AZN: Azerbaijani Manat
    BGN: Bulgarian Lev
    BRL: Brazilian Real
    BYN: Belarusian Ruble
    CAD: Canadian Dollar
    CHF: Swiss Franc
    CNY: Chinese Yuan
    CZK: Czech Koruna
    DKK: Danish Krone
    EGP: Egyptian Pound
    EUR: Euro
    GBP: British Pound Sterling
    GEL: Georgian Lari
    HKD: Hong Kong Dollar
    HUF: Hungarian Forint
    IDR: Indonesian Rupiah
    INR: Indian Rupee
    JPY: Japanese Yen
    KGS: Kyrgyzstani Som
    KRW: South Korean Won
    KZT: Kazakhstani Tenge
    MDL: Moldovan Leu
    NOK: Norwegian Krone
    NZD: New Zealand Dollar
    PLN: Polish Zloty
    QAR: Qatari Riyal
    RON: Romanian Leu
    RSD: Serbian Dinar
    SEK: Swedish Krona
    SGD: Singapore Dollar
    THB: Thai Baht
    TJS: Tajikistani Somoni
    TMT: Turkmenistan Manat
    TRY: Turkish Lira
    UAH: Ukrainian Hryvnia
    USD: United States Dollar
    UZS: Uzbekistani Som
    VND: Vietnamese Dong
    XDR: Special Drawing Rights (SDR)
    ZAR: South African Rand
